# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-snmp-agent}
  s.version = "0.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthew Palmer"]
  s.date = %q{2011-12-23}
  s.default_executable = %q{snmpd}
  s.description = %q{Write SNMP agents (servers) in pure Ruby}
  s.email = %q{mpalmer@hezmatt.org}
  s.executables = ["snmpd"]
  s.extra_rdoc_files = [
    "README.markdown",
    "TODO"
  ]
  s.files = [
    ".bzrignore",
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "README.markdown",
    "Rakefile",
    "TODO",
    "bin/snmpd",
    "lib/snmp/daemon.rb",
    "ruby-snmp-agent.gemspec",
    "test/agent_test.rb",
    "test/mib_node_test.rb",
    "test/misc_test.rb",
    "test/plugin_interface_test.rb",
    "test/proxy_test.rb",
    "test/snmp_protocol_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://theshed.hezmatt.org/rubysnmpd}
  s.licenses = ["GPL"]
  s.rdoc_options = ["--title", "SNMP Agent for Ruby"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A Ruby implementation of an SNMP agent}
  s.test_files = [
    "test/agent_test.rb",
    "test/mib_node_test.rb",
    "test/misc_test.rb",
    "test/plugin_interface_test.rb",
    "test/proxy_test.rb",
    "test/snmp_protocol_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, ["= 0.8.7"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rake>, ["= 0.8.7"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, ["= 0.8.7"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

